### PR TITLE
use requests library instead of urllib

### PR DESCRIPTION
**Pull request by baljamal**
I rewrote the image file download request using the requests library instead of urllib to overcome 403 forbidden HTTP error

### CODE REVIEW

**Comment by klauer** [comment]
Can you give more details?

I don't see a 403. I don't see the need to switch the library here and why `urllib` won't suffice. 
`requests` is a standalone library and will need to be installed separately / added to the requirements.

**Comment by baljamal** [comment]
urllib still giving me 403 forbidden error.
I wrote two sample codes one in urllib and the other one using requests, you can try and see

```
# urllib example

import pathlib
import urllib.request

IMAGE_ROOT = pathlib.Path.cwd()
image_url = 'https://download.beckhoff.com/download/Software/embPC-Control/CX51xx/CX51x0/CE/TC3/CBxx63_WEC7_HPS_v608w_TC31_B4024.35_v3.zip'
source_image_path = IMAGE_ROOT / pathlib.Path(image_url).name


def _download_status(block_num, blocksize, size):
    """Report download status from urlretrieve to the console."""
    if (block_num % 10) != 0:
        return

    percent = 100.0 * (block_num * blocksize) / size
    print(f"\rDownload status: {percent:.2f}%")


if __name__ == '__main__':
    urllib.request.urlretrieve(
        image_url,
        source_image_path,
        reporthook=_download_status
    )
```

```
# requests example

import requests
import pathlib
import shutil

IMAGE_ROOT = pathlib.Path.cwd()
image_url = 'https://download.beckhoff.com/download/Software/embPC-Control/CX51xx/CX51x0/CE/TC3/CBxx63_WEC7_HPS_v608w_TC31_B4024.35_v3.zip'
source_image_path = IMAGE_ROOT / pathlib.Path(image_url).name


if __name__ == '__main__':
    r = requests.get(image_url, verify=True, stream=True)
    r.raw.decode_content = True
    with open(source_image_path, 'wb') as f:
        shutil.copyfileobj(r.raw, f)

```

**Comment by klauer** [comment]
On which machine?
On which operating system?
On which network?
On VPN?

The original code has worked for me and for other engineers. I want to know what's different for _you_ that's making it fail.
We shouldn't jump to a different library without good reason.

**Comment by klauer** [comment]
So, I've started to see 403 errors now, too. Perhaps you were hitting a different CDN or there was a caching proxy or something on my end.

That being said, the core of the issue was not "the library is bad" but rather investigating _why_ the 403 error was occurring in the first place. It would be greatly appreciated in the future if you could add real context to your PR and issue description - a hand-waving "well this one works and this one doesn't" isn't really good enough.

I've dug a bit deeper now that I can reproduce your reported issue and have found that Beckhoff's servers are rejecting urllib's user agent. So the fix, then, is to adjust the user agent appropriately. I'll put up a separate PR retaining the existing library and allowing for user agent customization.

**Pull request closed without merging**
